### ISSUE TITLE
Concatenated files end up in an Array instead of an object

### ISSUE THREAD

**Issue by VincentVToscano** [Itrulia/gulp-concat-json#1]
The concatenated file displays a minified Array of all the data instead of an Object. If this is the intended behavior, please update your documentation. 

In contrast, view a non-gulp package that produces the expected output file and Object:

var jsonConcat  = require("json-concat");// npm install --save-dev json-concat

**Comment by Itrulia** [comment]
Multiple objects are an array. This is the correct behavior of JSON / JavaScript (as you can see [here](https://github.com/Itrulia/gulp-concat-json/blob/master/index.js#L29)), no need to update the documentation.

**Comment by VincentVToscano** [comment]
Thanks for your feedback. 
Then maybe this fits under a feature request:
**Add the option to output an Object or an Array as those are both allowed top-level or structured types.**
At this point, most users would expect to see a root/top-level Object vs an Array. esp. if they've viewed http://json.org/example. 
**_To clarify for future viewers, the code line referenced above speaks to manually building an Array – the module's intention – not the intended behavior of the JSON spec. This only partially satisfies the spec http://www.ietf.org/rfc/rfc4627.txt?number=4627
http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf
Parsers may use other top-level types while "application/json" media type allows only Object or Array.**_

**Comment by Itrulia** [comment]
This is the correct behaviour according to the spec.
You are confusing 2 things. You are thinking of associative arrays, but those are indexed arrays.

The link you provided proves you wrong:

```
{"menu": {
  "id": "file",
  "value": "File",
  "popup": {
    "menuitem": [
      {"value": "New", "onclick": "CreateNewDoc()"},
      {"value": "Open", "onclick": "OpenDoc()"},
      {"value": "Close", "onclick": "CloseDoc()"}
    ]
  }
}}
```

as you can see in the `menuitem`. This is an object since its associative, where multiple objects are an array. 

Since the module does only concatinate JSON files it will result in an array.

**Comment by VincentVToscano** [comment]
Thanks for the overview of the intended functionality of the plugin. Please re-read my last comment when you have a chance - feature request. Lots of luck with your future development.
